<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { Search, UserPlus, X } from 'lucide-vue-next'
import { adminApi, rows } from '@/api/services'
import { apiMessage } from '@/api/client'
import { dateTime, idempotencyKey, money } from '@/utils'
import type { User } from '@/types'
import AdminPageHeader from '@/components/AdminPageHeader.vue'
import UiStatus from '@/components/UiStatus.vue'
const users=ref<User[]>([]),query=ref(''),loading=ref(false),error=ref(''),dialog=ref<'create'|'balance'|''>(''),selected=ref<User>(),username=ref(''),email=ref(''),password=ref(''),amount=ref(0),direction=ref<'in'|'out'>('in'),reason=ref('')
async function load(){loading.value=true;try{users.value=rows(await adminApi.users({q:query.value}))}catch(e){error.value=apiMessage(e)}finally{loading.value=false}}
async function create(){try{await adminApi.create('users',{username:username.value,email:email.value,password:password.value,role:'user'});dialog.value='';username.value=email.value=password.value='';load()}catch(e){error.value=apiMessage(e)}}
function openBalance(u:User){selected.value=u;dialog.value='balance';amount.value=0;reason.value=''}
async function adjust(){if(!selected.value)return;try{await adminApi.adjustBalance(selected.value.id,{direction:direction.value,amount:amount.value,reason:reason.value,idempotency_key:idempotencyKey()});dialog.value='';load()}catch(e){error.value=apiMessage(e)}}
onMounted(load)
</script>
<template><AdminPageHeader title="用户与余额" description="查询注册用户，人工调整账户余额。"><button class="btn btn--primary btn--sm" @click="dialog='create'"><UserPlus :size="17"/>新建用户</button></AdminPageHeader><div class="admin-toolbar"><label class="search-field"><Search/><input v-model="query" placeholder="搜索用户名" @keyup.enter="load"/></label><button class="btn btn--secondary btn--sm" @click="load">查询</button></div><div v-if="error" class="alert alert--error">{{error}}</div><div class="data-panel"><div class="table-wrap"><table><thead><tr><th>用户</th><th>角色</th><th>状态</th><th>余额</th><th>注册时间</th><th></th></tr></thead><tbody><tr v-for="u in users" :key="u.id"><td><strong>{{u.username}}</strong><small>ID {{u.id}}</small></td><td>{{u.role==='admin'?'管理员':'普通用户'}}</td><td><UiStatus :value="u.status||'enabled'"/></td><td><strong>{{money(u.balance)}}</strong></td><td>{{dateTime(u.created_at)}}</td><td class="actions"><button class="btn btn--secondary btn--sm" @click="openBalance(u)">调整余额</button></td></tr></tbody></table></div><div v-if="!loading&&!users.length" class="state">暂无用户</div></div><div v-if="dialog" class="modal-backdrop" @click.self="dialog=''" role="presentation"><div class="modal"><div class="modal-head"><h2>{{dialog==='create'?'新建用户':`调整 ${selected?.username} 的余额`}}</h2><button class="icon-btn" @click="dialog=''" aria-label="关闭"><X/></button></div><form v-if="dialog==='create'" @submit.prevent="create"><label class="form-field"><span>用户名</span><input v-model="username" required/></label><label class="form-field"><span>邮箱</span><input v-model="email" type="email" required/></label><label class="form-field"><span>初始密码</span><input v-model="password" type="password" minlength="8" required/></label><button class="btn btn--primary btn--wide">创建用户</button></form><form v-else @submit.prevent="adjust"><div class="segmented"><button type="button" :class="{active:direction==='in'}" @click="direction='in'">增加余额</button><button type="button" :class="{active:direction==='out'}" @click="direction='out'">扣减余额</button></div><label class="form-field"><span>金额</span><input v-model.number="amount" type="number" min="0.01" step="0.01" required/></label><label class="form-field"><span>调整原因</span><textarea v-model="reason" required placeholder="请填写操作原因"/></label><button class="btn btn--primary btn--wide">确认调整</button></form></div></div></template>
